name: scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "17 4 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    name: OpenSSF Scorecard analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
